from gym_tasks.envs.VisualOlfactoryAttentionSwitchEnv import VisualOlfactoryAttentionSwitchEnv
from gym_tasks.envs.VisualOlfactoryAttentionSwitchNoBlankEnv import VisualOlfactoryAttentionSwitchNoBlankEnv
